### ISSUE TITLE
Add validation/defaults for installing / registering GM

### ISSUE THREAD

**Issue by harveyxia** [solo-io/gloo-mesh#1720]
Add validation for the following items for `meshctl install` and `meshctl cluster register`:

**Server pre-install**
- [x] validate that relay server address is a valid IP address

**Agent pre-install**
- [x] validate agent cert can be used to talk to server ([issue here](https://github.com/solo-io/gloo-mesh-enterprise/issues/892))

**Add the following defaults:**

- [x] for relay agent, default authority to serverAddress if serverAddress is a hostname, [issue here](https://github.com/solo-io/gloo-mesh-enterprise/issues/748)
- [x] integrate meshctl config file for all relevant commands

**TODOs**

- [x] fix `meshctl install` to make relayServer address optional unless registering mgmt cluster
- [ ] harden

**Comment by linsun** [comment]
Would be useful to validate version, which I run into as well given one has `v` and one doesn't.

```
export GLOO_MESH_VERSION=v1.1.0-beta16
export GLOO_MESH_ENTERPRISE_VERSION=1.1.0-beta20
```

Relay server addr - I assume it could be a host name if configured with a NLB or istio ingress gateway?

`--cluster-name` would be good to validate, especially istio is already installed? Does it have to match the cluster name specified in Istio's operator yaml?  I run into mismatch and spend quite some time to troubleshoot:

```
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: k3d-mp
```

Note: in Istio, we recommend users to specify clusterName for extending single cluster to multi cluster.

`relay-server-address` should be optional if managed cluster is same as mgmt cluster.
